name: Welcome New Contributors

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            Welcome to the Zen C community!

            Thanks for your first Pull Request! Please make sure you have read our [Contributing Guidelines](https://github.com/zenc-lang/zenc/blob/main/CONTRIBUTING.md).
            One of our maintainers will review your changes shortly.
